### PR TITLE
Implement Framebuffer Decorations

### PR DESCRIPTION
**Pull request by citrizon**
Just an implementation of Framebuffer Decorations (fbcondecor). Code is rewritten/refactored to make it work (maybe).

### CODE REVIEW

**Comment by Erwin-Iosef** [comment]
This looks sweet, have you tested it with fbsplash?

**Comment by citrizon** [comment]
Yeah i did tests using local repo and seems fine, however on remote repo (current pr), fb_cmap32 is redeclared. currently building the remote repo and i'll post the results.

**Comment by Erwin-Iosef** [comment]
I see. It's been some time since you posted this, have the developers reached out back?

I hope this gets approved soon. I've been recently and coincidentally wanting to install fbspalsh on my Linux system. Thank you so for building this.

**Comment by heftig** [comment]
Personally I'm not interested in fbcon at all, and you don't sound very confident about the quality of this code, but maybe @damentz has a different opinion.

**Comment by damentz** [comment]
Yep, I'm also not interested.  But there is one red flag that I don't think makes it suitable regardless:

> Note that userspace utilities are necessary in order to take advantage of these features.

I understand that you recently developed this feature, but if it takes an ecosystem to be useful, then I don't think this belongs in Zen.  This would be more of a toy you developed for yourself that you're trying to get merged into an alternative kernel.

Closing this MR.

**Comment by eegorov** [comment]
> Yeah i did tests using local repo and seems fine, however on remote repo (current pr), fb_cmap32 is redeclared. currently building the remote repo and i'll post the results.

What about user space tools?
For example in splashutils have been removed from Gentoo portage tree some time ago...

**Pull request closed without merging**
