### PR TITLE
Support for generic PS3 controller model CECHZC2U

### PR DESCRIPTION
**Pull request by KanuX-14**
Only works with cable. Can't connect through bluetooth yet.

### CODE REVIEW

**Comment by damentz** [comment]
I have mixed feelings on this pull request.  It appears that the CECHZC2U is a fake controller:

https://www.reddit.com/r/PS3/comments/h92ez7/is_this_controller_legit_model_cechzc2ua1/
https://gaming.stackexchange.com/questions/334517/how-can-i-tell-if-a-ps3-controller-may-be-fake

Everyone recommends returning and getting a refund to buy a real controller.

With that in mind, I don't think it's worth it to carry this patch in our zen-sauce branch since our recommendation would be to buy a real DualShock controller.

@heftig what are your thoughts?  In order to support this knock-off controller, the code had to be refactored just to add a small section of code at the bottom.  I don't like all this code churn as it will probably be the source of merge conflict grief in the future.

**Comment by damentz** [comment]
Ok, doing some more research, the `CECHZC2U` is the model number of the controller from Sony, but there's lots of fakes that reuse this model number despite not being official.  This means it presents itself differently to the host and is unsupported by the Sony driver by default.

This still brings up the issue that it's technically different and people have problems with the controller outside of Linux too, which is why the code below is required to support it:

```
if (!strcmp(hdev->name, "PS3 Controller"))
{
  sixaxis_report_0xf2_size = 64;
  sixaxis_report_0xf5_size = sixaxis_report_0xf2_size;
}
```

@KanuX-14 can you verify that your controller is fake or real?  I'd really prefer we don't add code for fakes.

**Comment by KanuX-14** [comment]
@damentz Yes, it's a generic controller made in China.
I understand that fake controllers aren't supported. But since PS3 controllers stopped being fabricated, it became hard to find one that is original.
The Linux kernel supports a lot of generic controllers. Where should I put this code?

**Comment by heftig** [comment]
> what are your thoughts? In order to support this knock-off controller, the code had to be refactored just to add a small section of code at the bottom. I don't like all this code churn as it will probably be the source of merge conflict grief in the future.

I think this should be submitted upstream as normal and go through code review there. I don't like the code as-is and I don't see why the ZEN kernel in particular should carry this patch.

**Comment by KanuX-14** [comment]
Original controllers are running perfectly. I got 1 week to test 2 models before trying a patch.
I know the code looks dirty, but were the only way to make the generic work.

**Comment by KanuX-14** [comment]
Tried my best to make a proper support, but just bugs and kernel crashes.
Closing this until I figure it out.

**Pull request closed without merging**
