### PR TITLE
Added exFAT support

### PR DESCRIPTION
**Pull request by diaevd**

### CODE REVIEW

**Comment by damentz** [comment]
What is the source of this patch?  I'd like to know that so we can make the commit message more helpful for future updates.

**Comment by diaevd** [comment]
This patch from https://github.com/rxrz/exfat-nofuse.git

**Comment by damentz** [comment]
Your patch has been merged: https://github.com/zen-kernel/zen-kernel/commit/d2c331bbdd1ef97d883cee6a229a4ec6dad1ce21

**Comment by heftig** [comment]
I've added this very same driver in past kernels, but could never test it. However, it was broken on x86 anyway (even though it compiled). Has this improved?

**Comment by diaevd** [comment]
I'm using it about few  month in previous 4.2 zen and its ok.
This driver realy from samsung android kernel (you can compare sources) with some litle changes... If you want i can reincpect code to the last samsung android kernel driver

**Comment by diaevd** [comment]
Can any one say me, need i do reinspect code from samsung (x86) android kernel and write extended comments about it for pull request will merge?

**Comment by damentz** [comment]
Can you test the module as it is merged now in 4.3 and tell us if it still works on your disks?  I don't have any exfat media handy so I can't do that for you.

**Comment by diaevd** [comment]
diabolo@veles:~$ uname -a
Linux veles 4.3.3-zen-bfs-gp70-2pe+ #5 ZEN SMP Wed Dec 23 12:13:42 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

i'm working under 4.3 after ZEN command pushed them on github :) and i'm add this module immediately. As i said earlier - i have a lot of devices formated to exFAT and use it each day. it's all working fine.

P.S. How can i connect to people who wrote msi-laptop driver (if you know)
P.P.S. exFAT module have pretty debug and i've use it each day :)

**Comment by diaevd** [comment]
happy that objection? I don't know what to do

**Comment by weedy** [comment]
This driver can't delete files properly.

Specifically it can't update the metadata to reflect it has deleted files. I have to run a fsck on windows to update the freespace counter.

My openelec box is much more robust, even handling permission (which is to say erroring just like the FAT driver). I would look at what openelec/raspberry pi are using.

**Pull request closed without merging**
